In [1]:
import pandas as pd

In [2]:
df =pd.read_csv(r'C:\Users\chand\OneDrive\Desktop\Data science\data-science-ai-and-ml\projects\credit\Credit (1).csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        4519 non-null   float64
 1   job        4515 non-null   object 
 2   marital    4518 non-null   object 
 3   education  4517 non-null   object 
 4   balance    4521 non-null   int64  
 5   housing    4518 non-null   object 
 6   duration   4519 non-null   float64
 7   campaign   4521 non-null   int64  
 8   approval   4521 non-null   object 
dtypes: float64(2), int64(2), object(5)
memory usage: 318.0+ KB


In [4]:
df.head(10)

age            job  marital  education  balance housing  duration  \
0  30.0     unemployed  married    primary     1787      no      79.0   
1  33.0       services  married  secondary     4789     yes     220.0   
2  35.0     management   single   tertiary     1350     yes     185.0   
3  30.0     management  married   tertiary     1476     yes     199.0   
4  59.0    blue-collar  married  secondary        0     yes     226.0   
5  35.0     management   single   tertiary      747      no     141.0   
6  36.0  self-employed  married   tertiary      307     yes     341.0   
7  39.0     technician  married  secondary      147     yes     151.0   
8  41.0   entrepreneur  married   tertiary      221     yes      57.0   
9  43.0       services  married    primary      -88     yes     313.0   

   campaign approval  
0         1       no  
1         1       no  
2         1       no  
3         4       no  
4         1       no  
5         2       no  
6         1       no  
7         2       no  
8         2       no  
9         1       no

In [5]:
df.tail(10)

age            job  marital  education  balance housing  duration  \
4511  46.0    blue-collar  married  secondary      668     yes    1263.0   
4512  40.0    blue-collar  married  secondary     1100     yes     660.0   
4513  49.0    blue-collar  married  secondary      322      no     356.0   
4514  38.0    blue-collar  married  secondary     1205     yes      45.0   
4515  32.0       services   single  secondary      473     yes     624.0   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

      campaign approval  
4511         2      yes  
4512         2       no  
4513         2       no  
4514         4       no  
4515         5       no  
4516         5       no  
4517         1       no  
4518        11       no  
4519         4       no  
4520         2       no

In [6]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
4516    False
4517    False
4518    False
4519    False
4520    False
Length: 4521, dtype: bool

In [7]:
df.duplicated().sum()

np.int64(1)

In [8]:
df.describe()

age       balance      duration     campaign
count  4519.000000   4521.000000  4.519000e+03  4521.000000
mean     41.381279   1422.657819  5.983921e+03     2.793630
std      13.966475   3009.638142  3.570683e+05     3.109807
min     -38.000000  -3313.000000 -7.990000e+02     1.000000
25%      33.000000     69.000000  1.040000e+02     1.000000
50%      39.000000    444.000000  1.850000e+02     2.000000
75%      49.000000   1480.000000  3.295000e+02     3.000000
max     416.000000  71188.000000  2.395650e+07    50.000000

In [9]:
df

age            job  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

      campaign approval  
0            1       no  
1            1       no  
2            1       no  
3            4       no  
4            1       no  
...        ...      ...  
4516         5       no  
4517         1       no  
4518        11       no  
4519         4       no  
4520         2       no  

[4521 rows x 9 columns]

In [10]:
df['age']

0       30.0
1       33.0
2       35.0
3       30.0
4       59.0
        ... 
4516    99.0
4517    57.0
4518    57.0
4519    28.0
4520    44.0
Name: age, Length: 4521, dtype: float64

In [11]:
df['balance']

0       1787
1       4789
2       1350
3       1476
4          0
        ... 
4516    -333
4517   -3313
4518     295
4519    1137
4520    1136
Name: balance, Length: 4521, dtype: int64

In [12]:
df.columns

Index(['age', 'job', 'marital', 'education', 'balance', 'housing', 'duration',
       'campaign', 'approval'],
      dtype='object')

In [13]:
df.education

0         primary
1       secondary
2        tertiary
3        tertiary
4       secondary
          ...    
4516    secondary
4517     tertiary
4518    secondary
4519    secondary
4520     tertiary
Name: education, Length: 4521, dtype: object

In [14]:
df.housing

0        no
1       yes
2       yes
3       yes
4       yes
       ... 
4516    yes
4517    yes
4518     no
4519     no
4520    yes
Name: housing, Length: 4521, dtype: object

In [15]:
df['age'].value_counts()

age
34.0     231
32.0     224
31.0     199
36.0     188
33.0     184
        ... 
13.0       1
84.0       1
416.0      1
410.0      1
99.0       1
Name: count, Length: 74, dtype: int64

In [16]:
df['balance'].value_counts()

balance
0       357
2        24
1        15
4        13
23       11
       ... 
5304      1
6969      1
572       1
164       1
4554      1
Name: count, Length: 2353, dtype: int64

In [17]:
df['age'].unique()

array([ 30.,  33.,  35.,  59.,  36.,  39.,  41.,  43.,  20.,  31.,  40.,
        56.,  37.,  25.,  38.,  42.,  44.,  26.,  55.,  67.,  53.,  68.,
        32.,  49.,  78.,   0.,  23.,  52.,  34.,  nan,  45.,  48.,  57.,
        54.,  63.,  51.,  29.,  50.,  27.,  60.,  28.,  21.,  58.,  22.,
        46.,  24.,  77.,  75.,  47.,  70.,  65.,  64.,  62.,  66.,  61.,
        19.,  81.,  83.,  80.,  71.,  72.,  69.,  79.,  73., -38.,  86.,
        74., 338.,  76.,  87.,  13.,  84., 416., 410.,  99.])

In [18]:
df['age'].nunique()

74

In [19]:
df.shape

(4521, 9)

In [20]:
df.dtypes

age          float64
job           object
marital       object
education     object
balance        int64
housing       object
duration     float64
campaign       int64
approval      object
dtype: object

In [21]:
marital_df =df[df['balance'] == 'marital']

In [22]:
marital_df =df[df['education'] == 'secondary']

In [23]:
marital_df

age          job  marital  education  balance housing  duration  \
1     33.0     services  married  secondary     4789     yes     220.0   
4     59.0  blue-collar  married  secondary        0     yes     226.0   
7     39.0   technician  married  secondary      147     yes     151.0   
10    39.0     services  married  secondary     9374     yes     273.0   
11    43.0       admin.  married  secondary      264     yes     113.0   
...    ...          ...      ...        ...      ...     ...       ...   
4514  38.0  blue-collar  married  secondary     1205     yes      45.0   
4515  32.0     services   single  secondary      473     yes     624.0   
4516  99.0     services  married  secondary     -333     yes     329.0   
4518  57.0   technician  married  secondary      295      no     151.0   
4519  28.0  blue-collar  married  secondary     1137      no     129.0   

      campaign approval  
1            1       no  
4            1       no  
7            2       no  
10           1       no  
11           2       no  
...        ...      ...  
4514         4       no  
4515         5       no  
4516         5       no  
4518        11       no  
4519         4       no  

[2305 rows x 9 columns]

In [24]:
marital_df[marital_df['age'] <= 18]

age          job  marital  education  balance housing  duration  \
38     0.0   management  married  secondary     3935     yes     765.0   
3809  13.0  blue-collar  married  secondary      161     yes     274.0   

      campaign approval  
38           1      yes  
3809         2       no

In [25]:
marital_df =df[(df['marital']== 'married')&
                 (df['age'] <= 18)&
                 (df['education'] == 'secondary' )]

In [26]:
marital_df

age          job  marital  education  balance housing  duration  \
38     0.0   management  married  secondary     3935     yes     765.0   
3809  13.0  blue-collar  married  secondary      161     yes     274.0   

      campaign approval  
38           1      yes  
3809         2       no

In [27]:
df.rename(columns= {'age': 'a'},inplace= True)

In [28]:
df

a            job  marital  education  balance housing  duration  \
0     30.0     unemployed  married    primary     1787      no      79.0   
1     33.0       services  married  secondary     4789     yes     220.0   
2     35.0     management   single   tertiary     1350     yes     185.0   
3     30.0     management  married   tertiary     1476     yes     199.0   
4     59.0    blue-collar  married  secondary        0     yes     226.0   
...    ...            ...      ...        ...      ...     ...       ...   
4516  99.0       services  married  secondary     -333     yes     329.0   
4517  57.0  self-employed  married   tertiary    -3313     yes    -153.0   
4518  57.0     technician  married  secondary      295      no     151.0   
4519  28.0    blue-collar  married  secondary     1137      no     129.0   
4520  44.0   entrepreneur   single   tertiary     1136     yes     345.0   

      campaign approval  
0            1       no  
1            1       no  
2            1       no  
3            4       no  
4            1       no  
...        ...      ...  
4516         5       no  
4517         1       no  
4518        11       no  
4519         4       no  
4520         2       no  

[4521 rows x 9 columns]

In [29]:
df.select_dtypes(include='object')

job  marital  education housing approval
0        unemployed  married    primary      no       no
1          services  married  secondary     yes       no
2        management   single   tertiary     yes       no
3        management  married   tertiary     yes       no
4       blue-collar  married  secondary     yes       no
...             ...      ...        ...     ...      ...
4516       services  married  secondary     yes       no
4517  self-employed  married   tertiary     yes       no
4518     technician  married  secondary      no       no
4519    blue-collar  married  secondary      no       no
4520   entrepreneur   single   tertiary     yes       no

[4521 rows x 5 columns]

In [30]:
num=df.select_dtypes(exclude='object')

In [31]:
num

a  balance  duration  campaign
0     30.0     1787      79.0         1
1     33.0     4789     220.0         1
2     35.0     1350     185.0         1
3     30.0     1476     199.0         4
4     59.0        0     226.0         1
...    ...      ...       ...       ...
4516  99.0     -333     329.0         5
4517  57.0    -3313    -153.0         1
4518  57.0      295     151.0        11
4519  28.0     1137     129.0         4
4520  44.0     1136     345.0         2

[4521 rows x 4 columns]

In [32]:
print(num.columns)

Index(['a', 'balance', 'duration', 'campaign'], dtype='object')


In [33]:
num.head()

a  balance  duration  campaign
0  30.0     1787      79.0         1
1  33.0     4789     220.0         1
2  35.0     1350     185.0         1
3  30.0     1476     199.0         4
4  59.0        0     226.0         1

In [34]:
num['a'].unique()

array([ 30.,  33.,  35.,  59.,  36.,  39.,  41.,  43.,  20.,  31.,  40.,
        56.,  37.,  25.,  38.,  42.,  44.,  26.,  55.,  67.,  53.,  68.,
        32.,  49.,  78.,   0.,  23.,  52.,  34.,  nan,  45.,  48.,  57.,
        54.,  63.,  51.,  29.,  50.,  27.,  60.,  28.,  21.,  58.,  22.,
        46.,  24.,  77.,  75.,  47.,  70.,  65.,  64.,  62.,  66.,  61.,
        19.,  81.,  83.,  80.,  71.,  72.,  69.,  79.,  73., -38.,  86.,
        74., 338.,  76.,  87.,  13.,  84., 416., 410.,  99.])

In [35]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()

df['job'] =le.fit_transform(df['job'])
df['balance'] =le.fit_transform(df['balance'])
df['housing'] =le.fit_transform(df['housing'])

In [36]:
num

a  balance  duration  campaign
0     30.0     1787      79.0         1
1     33.0     4789     220.0         1
2     35.0     1350     185.0         1
3     30.0     1476     199.0         4
4     59.0        0     226.0         1
...    ...      ...       ...       ...
4516  99.0     -333     329.0         5
4517  57.0    -3313    -153.0         1
4518  57.0      295     151.0        11
4519  28.0     1137     129.0         4
4520  44.0     1136     345.0         2

[4521 rows x 4 columns]

In [37]:
df

a  job  marital  education  balance  housing  duration  campaign  \
0     30.0   10  married    primary     1475        0      79.0         1   
1     33.0    7  married  secondary     2030        1     220.0         1   
2     35.0    4   single   tertiary     1303        1     185.0         1   
3     30.0    4  married   tertiary     1352        1     199.0         4   
4     59.0    1  married  secondary      274        1     226.0         1   
...    ...  ...      ...        ...      ...      ...       ...       ...   
4516  99.0    7  married  secondary      119        1     329.0         5   
4517  57.0    6  married   tertiary        0        1    -153.0         1   
4518  57.0    9  married  secondary      558        0     151.0        11   
4519  28.0    1  married  secondary     1187        0     129.0         4   
4520  44.0    2   single   tertiary     1186        1     345.0         2   

     approval  
0          no  
1          no  
2          no  
3          no  
4          no  
...       ...  
4516       no  
4517       no  
4518       no  
4519       no  
4520       no  

[4521 rows x 9 columns]

In [38]:
char=df.select_dtypes(exclude='object')

In [39]:
char

a  job  balance  housing  duration  campaign
0     30.0   10     1475        0      79.0         1
1     33.0    7     2030        1     220.0         1
2     35.0    4     1303        1     185.0         1
3     30.0    4     1352        1     199.0         4
4     59.0    1      274        1     226.0         1
...    ...  ...      ...      ...       ...       ...
4516  99.0    7      119        1     329.0         5
4517  57.0    6        0        1    -153.0         1
4518  57.0    9      558        0     151.0        11
4519  28.0    1     1187        0     129.0         4
4520  44.0    2     1186        1     345.0         2

[4521 rows x 6 columns]

In [40]:
clean_data =pd.concat([char],axis =1)

In [41]:
clean_data.to_csv('cr.csv',index= False)

In [42]:
clean_data.dropna(inplace=True)

In [43]:
x =clean_data.drop('balance',axis=1)
y =clean_data[['balance']]

In [44]:
x

a  job  housing  duration  campaign
0     30.0   10        0      79.0         1
1     33.0    7        1     220.0         1
2     35.0    4        1     185.0         1
3     30.0    4        1     199.0         4
4     59.0    1        1     226.0         1
...    ...  ...      ...       ...       ...
4516  99.0    7        1     329.0         5
4517  57.0    6        1    -153.0         1
4518  57.0    9        0     151.0        11
4519  28.0    1        0     129.0         4
4520  44.0    2        1     345.0         2

[4517 rows x 5 columns]

In [45]:
y

balance
0        1475
1        2030
2        1303
3        1352
4         274
...       ...
4516      119
4517        0
4518      558
4519     1187
4520     1186

[4517 rows x 1 columns]

In [46]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [47]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3613, 5), (904, 5), (3613, 1), (904, 1))

In [48]:

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [49]:
lr.score(x_train, y_train)

0.007617109614654449

In [50]:
lr.score(x_test, y_test)

0.007940831478222776

In [51]:
pred = lr.predict(x_test)

In [52]:
pred

array([[ 899.3902161 ],
       [ 849.99710681],
       [ 886.72657879],
       [ 732.16060902],
       [ 886.8114963 ],
       [ 908.65117559],
       [ 948.50264186],
       [ 849.99194699],
       [ 880.09572191],
       [ 852.86414093],
       [ 868.32437717],
       [ 839.0378067 ],
       [ 901.97269377],
       [ 886.83678453],
       [ 924.19137764],
       [1040.75888401],
       [ 939.4052444 ],
       [ 874.65637747],
       [ 889.92868197],
       [ 849.98838104],
       [ 896.41030178],
       [ 862.08570807],
       [ 911.8633595 ],
       [ 926.63435396],
       [ 865.38792509],
       [ 862.29184036],
       [ 933.44951039],
       [ 883.76952695],
       [ 899.45029435],
       [ 939.43420663],
       [ 924.15419312],
       [ 873.83067189],
       [ 874.46487239],
       [ 924.00372827],
       [ 890.20308269],
       [ 893.0973501 ],
       [ 917.91688967],
       [ 849.99548592],
       [ 927.05137812],
       [ 871.4705666 ],
       [ 865.43349642],
       [ 856.137

In [53]:
import joblib
joblib.dump(lr, 'model.lb')

['model.lb']

In [54]:
joblib.dump

<function joblib.numpy_pickle.dump(value, filename, compress=0, protocol=None)>

In [55]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [56]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3613, 5), (904, 5), (3613, 1), (904, 1))

In [57]:
from sklearn.svm import SVR
svr =SVR()
svr.fit(x_train, y_train)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [58]:
svr.score(x_train, y_train)

-0.09586602183485948

In [59]:
svr.score(x_test, y_test)

-0.07504915680662716

In [60]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [61]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3613, 5), (904, 5), (3613, 1), (904, 1))

In [62]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train, y_train)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\multiclass.py:213: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  y_type = type_of_target(y, input_name="y")


SVC()

In [63]:
svc.score(x_test, y_test)

C:\Users\chand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  type_true = type_of_target(y_true, input_name="y_true")


0.08185840707964602

In [64]:
from sklearn.datasets import load_iris
x,y = load_iris(return_X_y=True)
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [65]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [66]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [67]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [68]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [69]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [70]:
knn.score(x_train,y_train)

0.975

In [71]:
knn.predict(x_test)

array([0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 2, 1, 2, 2, 1, 1])