In [58]:
import pandas as pd

In [59]:
df =pd.read_csv('insurance.csv')

In [60]:
df =pd.read_csv(r'C:\Users\chand\OneDrive\Desktop\Data science\data-science-ai-and-ml\projects\insurance\insurance.csv')

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [62]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1333    False
1334    False
1335    False
1336    False
1337    False
Length: 1338, dtype: bool

In [63]:
df.duplicated().sum()

np.int64(1)

In [64]:
df.drop_duplicates(inplace=True)

In [65]:
df.duplicated().unique()

array([False])

In [66]:
df.duplicated().sum()

np.int64(0)

In [67]:
df.describe()

age          bmi     children       charges
count  1337.000000  1337.000000  1337.000000   1337.000000
mean     39.222139    30.663452     1.095737  13279.121487
std      14.044333     6.100468     1.205571  12110.359656
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.290000     0.000000   4746.344000
50%      39.000000    30.400000     1.000000   9386.161300
75%      51.000000    34.700000     2.000000  16657.717450
max      64.000000    53.130000     5.000000  63770.428010

In [68]:
df


age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [69]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [70]:
df.tail()

age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [71]:
df.region

0       southwest
1       southeast
2       southeast
3       northwest
4       northwest
          ...    
1333    northwest
1334    northeast
1335    southeast
1336    southwest
1337    northwest
Name: region, Length: 1337, dtype: object

In [72]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [73]:
df.age

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1337, dtype: int64

In [74]:
df['region']

0       southwest
1       southeast
2       southeast
3       northwest
4       northwest
          ...    
1333    northwest
1334    northeast
1335    southeast
1336    southwest
1337    northwest
Name: region, Length: 1337, dtype: object

In [75]:
df['children']

0       0
1       1
2       3
3       0
4       0
       ..
1333    3
1334    0
1335    0
1336    0
1337    0
Name: children, Length: 1337, dtype: int64

In [76]:
df['age']

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1337, dtype: int64

In [77]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    324
northeast    324
Name: count, dtype: int64

In [78]:
df['age'].value_counts()

age
18    69
19    67
46    29
52    29
50    29
47    29
48    29
51    29
45    29
20    29
24    28
27    28
28    28
25    28
23    28
49    28
54    28
53    28
22    28
21    28
26    28
31    27
41    27
44    27
43    27
42    27
29    27
30    27
40    27
32    26
33    26
57    26
34    26
55    26
56    26
35    25
58    25
37    25
59    25
39    25
36    25
38    25
62    23
60    23
63    23
61    23
64    22
Name: count, dtype: int64

In [79]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [80]:
df['region'].nunique()

4

In [81]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [82]:
df.shape

(1337, 7)

In [83]:
df[df['region'] == 'southwest']

age     sex   bmi  children smoker     region      charges
0      19  female  27.9         0    yes  southwest  16884.92400
12     23    male  34.4         0     no  southwest   1826.84300
15     19    male  24.6         1     no  southwest   1837.23700
18     56    male  40.3         0     no  southwest  10602.38500
19     30    male  35.3         0    yes  southwest  36837.46700
...   ...     ...   ...       ...    ...        ...          ...
1316   19  female  20.6         0     no  southwest   1731.67700
1329   52    male  38.6         2     no  southwest  10325.20600
1331   23  female  33.4         0     no  southwest  10795.93733
1332   52  female  44.7         3     no  southwest  11411.68500
1336   21  female  25.8         0     no  southwest   2007.94500

[325 rows x 7 columns]

In [84]:
southwest_df =df[df['region'] == 'southwest']

In [85]:
southwest_df


age     sex   bmi  children smoker     region      charges
0      19  female  27.9         0    yes  southwest  16884.92400
12     23    male  34.4         0     no  southwest   1826.84300
15     19    male  24.6         1     no  southwest   1837.23700
18     56    male  40.3         0     no  southwest  10602.38500
19     30    male  35.3         0    yes  southwest  36837.46700
...   ...     ...   ...       ...    ...        ...          ...
1316   19  female  20.6         0     no  southwest   1731.67700
1329   52    male  38.6         2     no  southwest  10325.20600
1331   23  female  33.4         0     no  southwest  10795.93733
1332   52  female  44.7         3     no  southwest  11411.68500
1336   21  female  25.8         0     no  southwest   2007.94500

[325 rows x 7 columns]

In [86]:
southwest_df =df[df['charges'] <= 16884]

In [87]:
southwest_df =df[df['bmi'] <= 27]

In [88]:
southwest_df =df[(df['region']== 'southwest')&
                 (df['bmi'] <= 27)&
                 (df['charges'] <= 16884)]

In [89]:
southwest_df


age     sex   bmi  children smoker     region    charges
15     19    male  24.6         1     no  southwest   1837.237
37     26    male  20.8         0     no  southwest   2302.300
99     38    male  19.3         0    yes  southwest  15820.699
191    36  female  26.2         0     no  southwest   4883.866
204    46    male  22.3         0     no  southwest   7147.105
...   ...     ...   ...       ...    ...        ...        ...
1287   36  female  25.9         1     no  southwest   5472.449
1295   20    male  22.0         1     no  southwest   1964.780
1302   25  female  20.8         1     no  southwest   3208.787
1316   19  female  20.6         0     no  southwest   1731.677
1336   21  female  25.8         0     no  southwest   2007.945

[71 rows x 7 columns]

In [90]:
df.rename(columns= {'age': 'a'},inplace= True)

In [91]:
df


a     sex     bmi  children smoker     region      charges
0     19  female  27.900         0    yes  southwest  16884.92400
1     18    male  33.770         1     no  southeast   1725.55230
2     28    male  33.000         3     no  southeast   4449.46200
3     33    male  22.705         0     no  northwest  21984.47061
4     32    male  28.880         0     no  northwest   3866.85520
...   ..     ...     ...       ...    ...        ...          ...
1333  50    male  30.970         3     no  northwest  10600.54830
1334  18  female  31.920         0     no  northeast   2205.98080
1335  18  female  36.850         0     no  southeast   1629.83350
1336  21  female  25.800         0     no  southwest   2007.94500
1337  61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [92]:
df.select_dtypes(include='object')

sex smoker     region
0     female    yes  southwest
1       male     no  southeast
2       male     no  southeast
3       male     no  northwest
4       male     no  northwest
...      ...    ...        ...
1333    male     no  northwest
1334  female     no  northeast
1335  female     no  southeast
1336  female     no  southwest
1337  female    yes  northwest

[1337 rows x 3 columns]

In [93]:
num =df.select_dtypes(include='object')

In [94]:
num


sex smoker     region
0     female    yes  southwest
1       male     no  southeast
2       male     no  southeast
3       male     no  northwest
4       male     no  northwest
...      ...    ...        ...
1333    male     no  northwest
1334  female     no  northeast
1335  female     no  southeast
1336  female     no  southwest
1337  female    yes  northwest

[1337 rows x 3 columns]

In [95]:
print(num.columns)

Index(['sex', 'smoker', 'region'], dtype='object')


In [96]:
num.head()

sex smoker     region
0  female    yes  southwest
1    male     no  southeast
2    male     no  southeast
3    male     no  northwest
4    male     no  northwest

In [97]:
num['sex'].unique()

array(['female', 'male'], dtype=object)

In [98]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()

df['region'] =le.fit_transform(df['region'])

In [99]:
num


sex smoker     region
0     female    yes  southwest
1       male     no  southeast
2       male     no  southeast
3       male     no  northwest
4       male     no  northwest
...      ...    ...        ...
1333    male     no  northwest
1334  female     no  northeast
1335  female     no  southeast
1336  female     no  southwest
1337  female    yes  northwest

[1337 rows x 3 columns]

In [100]:
df


a     sex     bmi  children smoker  region      charges
0     19  female  27.900         0    yes       3  16884.92400
1     18    male  33.770         1     no       2   1725.55230
2     28    male  33.000         3     no       2   4449.46200
3     33    male  22.705         0     no       1  21984.47061
4     32    male  28.880         0     no       1   3866.85520
...   ..     ...     ...       ...    ...     ...          ...
1333  50    male  30.970         3     no       1  10600.54830
1334  18  female  31.920         0     no       0   2205.98080
1335  18  female  36.850         0     no       2   1629.83350
1336  21  female  25.800         0     no       3   2007.94500
1337  61  female  29.070         0    yes       1  29141.36030

[1337 rows x 7 columns]

In [113]:
clean_data =pd.concat([num],axis =1)

In [114]:
clean_data

sex smoker     region
0     female    yes  southwest
1       male     no  southeast
2       male     no  southeast
3       male     no  northwest
4       male     no  northwest
...      ...    ...        ...
1333    male     no  northwest
1334  female     no  northeast
1335  female     no  southeast
1336  female     no  southwest
1337  female    yes  northwest

[1337 rows x 3 columns]

In [115]:
clean_data.to_csv('in')

In [116]:
clean_data.dropna(inplace=True)

In [117]:
x =clean_data.drop('smoker',axis=1)
y =clean_data[['smoker']]

In [118]:
x

sex     region
0     female  southwest
1       male  southeast
2       male  southeast
3       male  northwest
4       male  northwest
...      ...        ...
1333    male  northwest
1334  female  northeast
1335  female  southeast
1336  female  southwest
1337  female  northwest

[1337 rows x 2 columns]

In [119]:
y

smoker
0       yes
1        no
2        no
3        no
4        no
...     ...
1333     no
1334     no
1335     no
1336     no
1337    yes

[1337 rows x 1 columns]

In [120]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [121]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1069, 2), (268, 2), (1069, 1), (268, 1))

In [122]:
x_test

sex     region
900     male  northeast
1064  female  southwest
1256  female  northwest
298     male  northwest
237     male  southeast
...      ...        ...
534     male  southeast
542   female  southeast
760   female  northeast
1284    male  southwest
1285  female  northeast

[268 rows x 2 columns]

In [123]:
y_test

smoker
900      no
1064     no
1256     no
298     yes
237      no
...     ...
534      no
542      no
760      no
1284    yes
1285     no

[268 rows x 1 columns]

In [158]:

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [159]:
lr.score(x_train, y_train)

0.9317887551863151

In [160]:
lr.score(x_test, y_test)

0.9229151117708395

In [161]:
pred = lr.predict(x_test)

In [162]:
pred

array([ 1.92582295, -0.01716917,  1.31779514,  1.21009255,  1.02522339,
       -0.16748365, -0.03865548,  1.32291778,  1.71949712, -0.07270368,
        1.76327768,  0.86274384,  1.34684572, -0.04429995,  1.17617579,
        1.26131235,  1.17212646,  1.99665599, -0.0455729 ,  1.18932772,
        0.0349332 ,  1.81716957,  1.99473619,  1.67333424, -0.02112313,
        1.55656511,  2.24881361,  1.39816089,  1.76504646,  1.17251685])

In [136]:
import joblib
joblib.dump(lr, 'model.lb')

['model.lb']

In [137]:
joblib.dump

<function joblib.numpy_pickle.dump(value, filename, compress=0, protocol=None)>

In [138]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [139]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1069, 2), (268, 2), (1069, 1), (268, 1))

In [155]:
from sklearn.svm import SVR
svr = SVR()
svr.fit(x_train, y_train)

SVR()

In [156]:
svr.score(x_train, y_train)

0.948007896282296

In [157]:
svr.score(x_test, y_test)

0.9436331049662906

In [142]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [143]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1069, 2), (268, 2), (1069, 1), (268, 1))

In [153]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train, y_train)

SVC()

In [154]:
svc.score(x_test, y_test)

1.0

In [145]:
from sklearn.datasets import load_iris
x,y = load_iris(return_X_y=True)
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [146]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [147]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [148]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [149]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [150]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [151]:
knn.score(x_train,y_train)

0.9583333333333334

In [152]:
knn.predict(x_test)

array([2, 0, 1, 1, 1, 0, 0, 1, 2, 0, 2, 1, 1, 0, 1, 1, 1, 2, 0, 1, 0, 2,
       2, 2, 0, 2, 2, 1, 2, 1])